name: Weekly Update
on:
  schedule:
    - cron: '0 3 * * 5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 自动下载iptvz源并生成可用的m3u
        run: |
          # 下载源
          curl -s "https://raw.githubusercontent.com/q1017673817/iptvz/main/%E7%BB%84%E6%92%AD_%E6%B9%96%E5%8D%97%E7%94%B5%E4%BF%A1.txt" -o source.txt

          # 生成可用的 result.m3u
          echo '#EXTM3U x-tvg-url="https://raw.githubusercontent.com/skipandgoon/iptv-api/master/output/epg/epg.gz"' > output/result.m3u

          while IFS=, read -r name url || [ -n "$name" ]; do
            if [[ "$name" == *#genre#* ]]; then
              group="${name%%,*}"
              continue
            fi
            if [[ -z "$name" || -z "$url" ]]; then
              continue
            fi
            echo "#EXTINF:-1 tvg-name=\"$name\" tvg-logo=\"https://cdn.jsdelivr.net/gh/skipandgoon/MyIcons/icons/TV/$name.png\" group-title=\"$group\",$name" >> output/result.m3u
            echo "$url" >> output/result.m3u
          done < source.txt

      - name: 提交更新
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add output/result.m3u
          git commit -m "更新 IPTV 源"
          git push
