name: 更新直播源
on:
  schedule:
    - cron: '0 3 * * 5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 下载源+生成分组+港澳台拼音排序
        run: |
          # 下载源
          curl -s "https://raw.githubusercontent.com/q1017673817/iptvz/main/%E7%BB%84%E6%92%AD_%E6%B9%96%E5%8D%97%E7%94%B5%E4%BF%A1.txt" -o source.txt
          
          # 定义输出文件
          output="output/result.m3u"
          echo '#EXTM3U x-tvg-url="https://ghproxy.com/https://raw.githubusercontent.com/skipandgoon/iptv-api/master/output/epg/epg.gz"' > $output

          # 临时文件分类
          cctv=""
          ws=""
          gat=""

          while IFS=, read -r name url || [ -n "$name" ]; do
            [[ -z "$name" || -z "$url" ]] && continue
            logo="https://cdn.jsdelivr.net/gh/skipandgoon/MyIcons/icons/TV/$name.png"

            if [[ "$name" == CCTV* ]]; then
              cctv+="#EXTINF:-1 tvg-name=\"$name\" tvg-logo=\"$logo\" group-title=\"📺 央视频道\",$name\n$url\n"
            elif [[ "$name" == *卫视 ]]; then
              ws+="#EXTINF:-1 tvg-name=\"$name\" tvg-logo=\"$logo\" group-title=\"📡 卫视频道\",$name\n$url\n"
            else
              gat+="$name|$url|$logo\n"
            fi
          done < source.txt

          # 输出央视 + 卫视
          echo -e "$cctv" >> $output
          echo -e "$ws" >> $output

          # 港澳台按【拼音排序】后输出
          echo -e "$gat" | sort | while IFS="|" read -r name url logo; do
            echo "#EXTINF:-1 tvg-name=\"$name\" tvg-logo=\"$logo\" group-title=\"☘️ 港澳台/其他\",$name" >> $output
            echo "$url" >> $output
          done

      - name: 提交更新
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add output/result.m3u
          git commit -m "更新直播源"
          git push
